export const PLANET_DATA = {
  sun: {
    name: "Sun",
    color: "#ffcc00",
    size: 5,
    distance: 0,
    speed: 0,
    description: "The Sun is the star at the center of our Solar System. It is a nearly perfect sphere of hot plasma.",
    stats: {
      diameter: "1,392,700 km",
      mass: "1.989 × 10^30 kg",
      gravity: "26.93 m/s²",
      temperature: "5,500°C (Surface)",
      orbitalPeriod: "N/A",
      rotationPeriod: "25.4 days",
      moons: 0,
      atmosphere: "Hydrogen, Helium, Helium-3",
    },
  },
  mercury: {
    name: "Mercury",
    color: "#a5a5a5",
    size: 0.8,
    distance: 10,
    speed: 0.04,
    description: "Mercury is the smallest planet in our solar system and the closest to the Sun.",
    stats: {
      diameter: "4,879 km",
      mass: "3.30 × 10^23 kg",
      gravity: "3.7 m/s²",
      temperature: "167°C (Average)",
      orbitalPeriod: "88 days",
      rotationPeriod: "58.6 days",
      moons: 0,
      atmosphere: "Thin exosphere",
    },
  },
  venus: {
    name: "Venus",
    color: "#e3bb76",
    size: 1.2,
    distance: 15,
    speed: 0.015,
    description: "Venus is the hottest planet in our solar system, with a surface temperature hot enough to melt lead.",
    stats: {
      diameter: "12,104 km",
      mass: "4.87 × 10^24 kg",
      gravity: "8.87 m/s²",
      temperature: "464°C",
      orbitalPeriod: "225 days",
      rotationPeriod: "243 days",
      moons: 0,
      atmosphere: "Carbon dioxide, Nitrogen",
    },
  },
  earth: {
    name: "Earth",
    color: "#2271b3",
    size: 1.3,
    distance: 20,
    speed: 0.01,
    description: "Earth is our home planet and the only known planet to support life.",
    stats: {
      diameter: "12,742 km",
      mass: "5.97 × 10^24 kg",
      gravity: "9.8 m/s²",
      temperature: "15°C (Average)",
      orbitalPeriod: "365 days",
      rotationPeriod: "24 hours",
      moons: 1,
      atmosphere: "Nitrogen, Oxygen",
    },
  },
  mars: {
    name: "Mars",
    color: "#e27b58",
    size: 1,
    distance: 26,
    speed: 0.008,
    description: "Mars is a dusty, cold, desert world with a very thin atmosphere.",
    stats: {
      diameter: "6,779 km",
      mass: "6.39 × 10^23 kg",
      gravity: "3.72 m/s²",
      temperature: "-65°C (Average)",
      orbitalPeriod: "687 days",
      rotationPeriod: "24.6 hours",
      moons: 2,
      atmosphere: "Carbon dioxide, Nitrogen",
    },
  },
  jupiter: {
    name: "Jupiter",
    color: "#d39c7e",
    size: 3.5,
    distance: 38,
    speed: 0.004,
    description: "Jupiter is the largest planet in our solar system—more than twice as massive as all the other planets combined.",
    stats: {
      diameter: "139,820 km",
      mass: "1.89 × 10^27 kg",
      gravity: "24.79 m/s²",
      temperature: "-125°C",
      orbitalPeriod: "12 years",
      rotationPeriod: "9.9 hours",
      moons: 95,
      atmosphere: "Hydrogen, Helium",
    },
  },
  saturn: {
    name: "Saturn",
    color: "#c5ab7b",
    size: 3,
    distance: 50,
    speed: 0.003,
    description: "Saturn is unique for its complex and beautiful ring system.",
    stats: {
      diameter: "116,460 km",
      mass: "5.68 × 10^26 kg",
      gravity: "10.44 m/s²",
      temperature: "-140°C",
      orbitalPeriod: "29 years",
      rotationPeriod: "10.7 hours",
      moons: 146,
      atmosphere: "Hydrogen, Helium",
    },
  },
  uranus: {
    name: "Uranus",
    color: "#b5e3e3",
    size: 2,
    distance: 62,
    speed: 0.002,
    description: "Uranus is an ice giant with a unique tilt, rotating on its side.",
    stats: {
      diameter: "50,724 km",
      mass: "8.68 × 10^25 kg",
      gravity: "8.69 m/s²",
      temperature: "-195°C",
      orbitalPeriod: "84 years",
      rotationPeriod: "17.2 hours",
      moons: 27,
      atmosphere: "Hydrogen, Helium, Methane",
    },
  },
  neptune: {
    name: "Neptune",
    color: "#4b71e3",
    size: 2,
    distance: 70,
    speed: 0.001,
    description: "Neptune is the most distant major planet in our solar system.",
    stats: {
      diameter: "49,244 km",
      mass: "1.02 × 10^26 kg",
      gravity: "11.15 m/s²",
      temperature: "-201°C",
      orbitalPeriod: "165 years",
      rotationPeriod: "16.1 hours",
      moons: 14,
      atmosphere: "Hydrogen, Helium, Methane",
    },
  },
};
